### ISSUE TITLE
Demo Site SSL Cert expired

### ISSUE THREAD

**Issue by worldworm** [anderspitman/fibridge-proxy-rs#2]
your demo page is not available. Your SSL Cert expired.

https://fbrg.xyz/

If the URL has changed, please open a pull request at
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

awesome-selfhosted/awesome-selfhosted#1767

**Comment by anderspitman** [comment]
Thanks for the heads up @worldworm! I renewed the cert and it should be good to go. Let me know if you run into any further problems.
